[build]
  command = "python app.py"  # Replace with your Flask application entry point
  publish = "path/to/your/application"  # Replace with the path to your Flask application

[build.environment]
  PYTHON_VERSION = "3.8"  # Replace with your desired Python version

[dev]
  command = "python app.py"  # Replace with your Flask application entry point

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[build.processing]
  command = "python static/DB/init.py"  # Replace with your database script
  description = "Running database script"
